version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run:
          name: "Install build system dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install python3 python3-setuptools python3-pip
            python3 -m pip install --user build
      - checkout
      - run:
          name: "Build COMPASS python package"
          command: |
            python3 -m build --sdist --wheel .

workflows:
  build-workflow:
    jobs:
      - build
